const CampusActionType = {
  FETCH_ALL_CAMPUSES: "FETCH_ALL_CAMPUSES",
  FETCH_SINGLE_CAMPUS: "FETCH_SINGLE_CAMPUS",
  ADD_CAMPUS: "ADD_CAMPUS",
  DELETE_CAMPUS: "DELETE_CAMPUS",
  EDIT_CAMPUS: "EDIT_CAMPUS",
};

export default CampusActionType;
