const StudentActionType = {
  FETCH_ALL_STUDENTS: "FETCH_ALL_STUDENTS",
  FETCH_SINGLE_STUDENT: "FETCH_SINGLE_STUDENT",
  ADD_STUDENT: "ADD_STUDENT",
  DELETE_STUDENT: "DELETE_STUDENT",
  EDIT_STUDENT: "EDIT_STUDENT",
};

export default StudentActionType;
